<?= $this->doctype() ?>
<?= $this->megamenu()->load();   ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->megamenu()->GetCurrentTitleByUrl()." | ".$this->SiteConfig()->Title())->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])                   
            ->prependStylesheet('/css/mmenu.css')        
            ->prependStylesheet($this->basePath('components/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('components/font-awesome/css/fontawesome-all.min.css'))        
            ->prependStylesheet($this->basePath('/js/jQuery.mmenu/dist/jquery.mmenu.all.css'))                                               
            
        ?>
        <?= $this->headScript()
            ->prependFile($this->basePath('js/common.js'))        
            ->prependFile($this->basePath('components/bootstrap/js/bootstrap.min.js'))            
            ->prependFile($this->basePath('/js/jQuery.mmenu/dist/translations/ru/jquery.mmenu.ru.js'))                    
            ->prependFile($this->basePath('/js/jQuery.mmenu/dist/jquery.mmenu.all.js'))                    
            ->prependFile($this->basePath('components/jquery/jquery.min.js'))                
        ?>
    </head>
    <body>        
	<div class="header">
		<a href="#menu"></a>                
                <?= $this->megamenu()->RenderQuickMenu();?>
	</div>     
        <?= $this->megamenu()->RenderMegaMenu("menu");?>
        <div class="container-fluid">
            <?php echo $this->mess()->renderErrorMessages(); ?>
            <?= $this->content ?>
            <?php echo $this->megamenu()->RenderBreadcrumbs(); ?>
            <hr>
            <footer>
                <p>&copy; 2011 - <?= date('Y') ?> by <a target="_blank"href="https://грибовы.рф">Pavel Gribov</a></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
        <script>
            <?= $this->megamenu()->ViewJSMenu("menu") ?>
        </script>    
    </body>
</html>
