<?php use Application\Common\CommonFunctions;?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Учет ТМЦ в организации')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])                   
            ->prependStylesheet($this->basePath('components/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet('/css/login.css')
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('components/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('components/jquery/jquery.min.js'))
            ->prependFile($this->basePath('js/common.js'))
        ?>
    </head>
<body>    
    <?php echo $this->mess()->renderErrorMessages(); ?>
    <?= $this->content ?>
    <?= $this->inlineScript() ?>    
</body>
</html>        
