<div style="margin-top:10px">
  <table id="list1"></table>
  <div id="pager1"></div>
</div>
<script>
$(document).ready(function(){				
			$("#list1").jqGrid({
                                url:'/user/listusers',
				datatype: "json",				
                                colNames:['Id','Архив','Логин','Пароль','Действия'],
                                colModel:[
                                        {name:'id',index:'id', width:55,editable:false,search: false,fixed:true},
                                        {name:'archive',index:'archive', fixed:true,width:55,editable:true,formatter: 'checkbox',edittype: 'checkbox', editoptions: {value: '1:0'},search: false},
                                        {name:'login',index:'login', width:100,editable:true},
                                        {name:'password',edittype: 'password',index:'password', width:100,editable:true,search: false},
                                        {name:'myac', width:60, fixed:true, sortable:false, resize:false, formatter:'actions',formatoptions:{keys:true},search: false}
                                ],  
                                loadError: function (jqXHR) {
                                    $().toastmessage('showSuccessToast',jqXHR.responseText);
                                },   
				sortname: 'id',
				sortorder: 'asc',
				sortable: true,
				height: 'auto',
				pager: '#pager1',
				viewrecords: true,
				gridview: true,
                                guiStyle: "bootstrap4",
                                iconsOverText: true,
				autowidth: true,
				altRows: true,
				closeOnEscape: true,
				autoresizeOnLoad: true,
				headertitles: true,                                                                                                
                                editurl:"/user/listusers",
                                caption:"Справочник пользователей"
			}).jqGrid("gridResize");
			$("#list1").navGrid("#pager1",{                                
				search: true,
				add: true,
				edit: true,
				del: true,
				refresh: true
				},
				{errorTextFormat: commonError}, //edit options
				{errorTextFormat: commonError}, //add options
				{errorTextFormat: commonError}, //delete options
				{
					multipleSearch: true
					,closeAfterSearch: true
					,closeAfterReset: true									
				}
			);                        
                        jQuery('#list1').jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false});						
                        // Выбор колонок                        
			$("#list1").navButtonAdd('#pager1',{
				caption: "<i class=\"fa fa-table\" aria-hidden=\"true\"></i>",
				title: "Выбор колонок",				
                                buttonicon: 'none',
				onClickButton: function () {
					$("#list1").jqGrid('columnChooser');
				}
			});	
                        //Делаем таблицу резиновой
                        BindResizeble("#list1","#maincontent");
		});	    
function commonError(data) {
    console.log(data.responseText);
    return data.responseText;
}                
</script>    